name: Deploy Documentation

env:
  DOCS_CNAME: 'laravel-starter.entapp.northwestern.edu'
  NODE_VERSION: '25'
  PNPM_VERSION: '11.x.x'

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout Repository
        uses: actions/checkout@v7
        with:
          ref: ${{ github.ref_name }}

      - name: 🔁 Setup Environment
        uses: ./.github/actions/common-setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
          docs-only: true
          build-docs: true

      - name: 📚 Deploy Docs
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/dist
          cname: ${{ env.DOCS_CNAME }}
